# fly.toml app configuration file generated for spentoday-backend on 2023-07-11T15:40:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spentoday-backend"
primary_region = "waw"

[build]
  dockerfile = "./Backend/Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
